language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx

# Run build for all the supportet trains
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: stable
  fast-finish: true

# Add clippy
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
      fi
  - export PATH=$PATH:~/.cargo/bin

# The main build
script:
  - cargo build
  - cargo test
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" && $CLIPPY ]]; then
        cargo clippy
      fi