language: rust
cache: cargo

# Run build for all the supportet trains
rust:
  - nightly
  - beta
  - stable

matrix:
  include:
    - rust: nightly-2018-04-15
      env:
        - CLIPPY_VERSION=0.0.194
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt -- --write-mode=diff
        - cargo clippy -- -D clippy
  allow_failures:
    - rust: stable
  fast-finish: true

# The main build
script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose